### ISSUE TITLE
Support Zhihu-style CSS

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#391]
See posts:

- https://v2ex.com/t/822425
- https://v2ex.com/t/819780

and repo:

- https://github.com/viewweiwu/v2ex-zhihu-theme

We can add it as both a Casnode admin config (so the site owner can change the global CSS) and also a user config like:

![image](https://user-images.githubusercontent.com/3787410/147376600-7be641b0-73e3-4f59-a8fa-cd2aa68eee4a.png)

**Comment by viewweiwu** [comment]
@hsluoyz 
I am the author of v2ex-zhihu-them.
Thanks for the endorsement of v2ex-zhihu-theme.

I was contacted by the author of casnode.
I am very happy to be compatible with casnode.

There are still some problems with the dark theme, but I believe that casnode will support the new theme style soon.


![image](https://user-images.githubusercontent.com/14287892/148037836-9705d68f-2037-43ce-aa93-1dedd2f4ef42.png)

**Comment by hsluoyz** [comment]
@viewweiwu thanks for contributing to Casnode! Your v2ex-zhihu-theme is amazing and will generate great impact for Casnode users!

**Comment by viewweiwu** [comment]
PR: [402](https://github.com/casbin/casnode/pull/402)

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casnode/pull/402
