### ISSUE TITLE
There seems to be a display bug here

### ISSUE THREAD

**Issue by erdengk** [casbin/casibase#395]
Step 1 : click docker to install

![image](https://user-images.githubusercontent.com/37730787/147824009-e09d6676-9955-40c8-bac9-ffbc0085629e.png)

Step 2: click language conversion to select another language

![image](https://user-images.githubusercontent.com/37730787/147824034-310ac1a8-efd8-45ff-bc5b-d96c33ecf397.png)

You will get a 404 prompt

![image](https://user-images.githubusercontent.com/37730787/147824095-466bd466-ee0b-4ec3-94d2-c1f300a4625a.png)

![image](https://user-images.githubusercontent.com/37730787/147824071-d9c1b4e6-086f-420b-9e1b-b6e0e620649e.png)

**Comment by hsluoyz** [comment]
@erdengk fixed in: https://github.com/casnode/casnode-website/commit/a4f12948876c9b49fb670e05c1c7698af3252892
