### ISSUE TITLE
BUG：After the administrator adds a category, the home page cannot be displayed normally. 

### ISSUE THREAD

**Issue by erdengk** [casbin/casibase#397]
After the administrator adds a category, the home page cannot be displayed normally. (it cannot be displayed in Google browser or other browsers)
1. Add category by administrator

![image](https://user-images.githubusercontent.com/37730787/147846382-1b10a13a-363d-4232-84af-ac32734b2b03.png)

![image](https://user-images.githubusercontent.com/37730787/147846395-e792e197-e8de-4b6b-bbfd-2dc7b4f90d2c.png)

2. Return to the home page and cannot be displayed normally

![image](https://user-images.githubusercontent.com/37730787/147846432-c669aae7-0516-41ea-9e50-4f32c44382f5.png)

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casnode/commit/eb436e4eb1b331564d02f8dd3020f0510fe722ea
