### ISSUE TITLE
There seems to be a bug when asking questions.

### ISSUE THREAD

**Issue by erdengk** [casbin/casibase#399]
After running the project. Log in as an administrator, click to ask questions and enter content. There is no response after submission.

![image](https://user-images.githubusercontent.com/37730787/147909203-b1ccb100-aa49-4713-a9d7-357d905709e1.png)

**Comment by hsluoyz** [comment]
@erdengk plz reproduce this issue in: https://forum.casbin.com/ and record a video.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casnode/commit/3279fd1bc435400c7fe4e01b00588a368fcf0009
