### ISSUE TITLE
[Feature] The project UI can be further optimized

### ISSUE THREAD

**Issue by erdengk** [casbin/casibase#400]
When accessing a project with a PC browser, the UI does not adapt when the window shrinks.

![image](https://user-images.githubusercontent.com/37730787/147909582-ee47b4e9-9e7a-4a52-a102-4d0b739a877f.png)

**Comment by hsluoyz** [comment]
@seriouszyx

**Comment by MayankMittal1** [comment]
@hsluoyz Hi i want to contribute in casbin and I'm interested in taking up this issue

**Comment by MayankMittal1** [comment]
@erdengk this is not an issue, it is already responsive, if you are using chrome developer tools to view the website in responsive mode, then reload the page and it will be fine.
![Screenshot from 2022-04-12 17-56-58](https://user-images.githubusercontent.com/74496738/162962396-a2c8e7ff-31be-4acc-abaa-a6b9aa5d5391.png)

**Comment by erdengk** [comment]
@MayankMittal1 
you are right. Now the ui is responsive.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/37730787/162970037-892fe1d0-4037-479e-a312-66af0909ef2f.png">
