### ISSUE TITLE
There is a bug in the upload file function

### ISSUE THREAD

**Issue by erdengk** [casbin/casibase#401]
There is a bug in the upload file function. After clicking upload file, the file is uploaded successfully, but it is not displayed in the file library.

![image](https://user-images.githubusercontent.com/37730787/147910819-2d511864-5977-4128-9a56-4b60dfdbf538.png)

![image](https://user-images.githubusercontent.com/37730787/147910887-49bf4a89-85d4-4f5c-b0cd-9f70b77437af.png)

**Comment by erdengk** [comment]
![Uploading image.png…]()

**Comment by erdengk** [comment]
An OSS error occurred when I uploaded a picture in the [casino](https://forum.casbin.com/)

![image](https://user-images.githubusercontent.com/37730787/147910988-cceb85b9-e7fd-4e78-94b5-a72fd1aa2cd6.png)

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casnode/commit/1f9f095334413326e6141821fb213b0ffed3d9a7

**Comment by hsluoyz** [comment]
@erdengk see image upload: https://forum.casbin.com/t/561

![image](https://user-images.githubusercontent.com/3787410/147946913-41547742-f509-4537-a161-9eea300b0919.png)
