### ISSUE TITLE
There seems to be a bug on the personal information page

### ISSUE THREAD

**Issue by erdengk** [casbin/casibase#405]
![image](https://user-images.githubusercontent.com/37730787/149086168-a92b0f54-611a-442f-840e-060c52931742.png)

When you click the following button.

The left avatar cannot be displayed normally

![image](https://user-images.githubusercontent.com/37730787/149086442-82ad98e1-c406-4518-af7d-51654e5b41b2.png)

**Comment by hsluoyz** [comment]
@erdengk fixed in: https://github.com/casbin/casnode/commit/c36134eb060013557740a7dbb5d0ec1f3bc38f61
