### ISSUE TITLE
The coins won't be updated timely after posting

### ISSUE THREAD

**Issue by Nekotoxin** [casbin/casibase#416]
<img width="1037" alt="屏幕截图 2022-02-23 231457" src="https://user-images.githubusercontent.com/75596353/155348667-8fa1f0a2-d9b7-4df2-b9a2-088f5cee2168.png">
<img width="1022" alt="屏幕截图 2022-02-23 231503" src="https://user-images.githubusercontent.com/75596353/155348676-780a5578-2c28-4dbb-8d7a-d7da5bd545bc.png">
<img width="1139" alt="屏幕截图 2022-02-23 231450" src="https://user-images.githubusercontent.com/75596353/155348690-30166a2f-e786-4c59-bd39-b9f1a293e7c6.png">

**Comment by hsluoyz** [comment]
@Nekotoxin can you fix it?

**Comment by Nekotoxin** [comment]
> @Nekotoxin can you fix it?

I'll try
