### ISSUE TITLE
Member No. is always zero bug

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#422]
See: https://forum.casbin.com/member/leiboy

![image](https://user-images.githubusercontent.com/3787410/155866670-70faf113-4cd3-4684-a1bd-9e5179d7ac3e.png)

We expect to be:

![image](https://user-images.githubusercontent.com/3787410/155866678-ed9c19c9-2fc4-4c3b-a07a-5cc8798494a2.png)

**Comment by hsluoyz** [comment]
@Nekotoxin

**Comment by Nekotoxin** [comment]
fixed at [casdoor pr#516](https://github.com/casdoor/casdoor/pull/516)
