### ISSUE TITLE
Use different document titles for each page to have better SEO result

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#431]
See: https://www.google.com/search?q=casbin+site%3Aforum.casbin.com

Most of the titles are the default one, which is meaningless:

![image](https://user-images.githubusercontent.com/3787410/156411445-4fcc58f1-60ea-4655-afa3-3ef9b6aa6b0e.png)

**Comment by hsluoyz** [comment]
@Nekotoxin

**Comment by Shivansh-yadav13** [comment]
Can I contribute.
