### ISSUE TITLE
Improve the SEO for search engines like Baidu

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#435]
Our SEO is very bad, there are already a lot of user requests to improve it:

- https://forum.casbin.com/t/75
- https://forum.casbin.com/t/638

![image](https://user-images.githubusercontent.com/3787410/158122062-d7a6788b-17df-477c-893d-2b5b26cdbc84.png)

![image](https://user-images.githubusercontent.com/3787410/158122076-271b102d-dd4b-46be-9abe-5ba54d906843.png)

The TDK is also very bad:

![image](https://user-images.githubusercontent.com/3787410/158122231-ad74ab13-d946-4f99-b46a-949b115c21e2.png)

Even for the contents indexed by the search engine, the result quality is also bad:

See our Casnode site: https://www.baidu.com/s?wd=site%3Aforum.casbin.com compared with Discuz X 3.4 site: https://www.baidu.com/s?wd=site%3Adiscuz.net

Their contents are very high-quality:

![image](https://user-images.githubusercontent.com/3787410/156882757-5664d7cb-192f-4efe-a8b1-a2b970b99eb2.png)

But most of our contents are useless, like:

-  全部回复 回复总数 1 9个月前 回复了 wellwell 创建的主题 
- 4个月前· 528次点击 这是一个创建于 134天前的主题,其中的信息可能已经有所发展或是发生改变.

I know we have such texts in the page, but can we avoid them showing up in the search engine result digest? The best thing to show is the content of the topic and replies. There should something we can do in the code to improve the SEO for this forum software.

![image](https://user-images.githubusercontent.com/3787410/156882791-bb6d67b5-6abd-48a6-b4e7-cb4dc635dcdb.png)

**Comment by hsluoyz** [comment]
@RyaoChengfeng plz work on this

BTW, what's your QQ?

**Comment by RyaoChengfeng** [comment]
My QQ: 742790355

Yang Luo ***@***.***> 于2022年3月22日周二 18:47写道：
