### ISSUE TITLE
The current SSR browsers won't close

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#441]
Now we have a SSR mechanism based on Headless Chrome: https://casnode.org/docs/server-side-rendering

But it has bug: the browsers won't close and will take up the resources forever. We want to have a browser pool (like N browser instances in the pool, N can be configured), each SSR request will go into a random instance in the pool.

![image](https://user-images.githubusercontent.com/3787410/156909903-69d35050-0432-47fd-a444-7ca91e171baa.png)

https://github.com/casbin/casnode/blob/815a6a068a5bf654d58e0e9e92ac7fbd602ddc62/routers/filter_ssr.go#L65-L106

**Comment by Nekotoxin** [comment]
I'll work on it
