### ISSUE TITLE
It is recommended to put all configuration (including front-end configuration) on the back end

### ISSUE THREAD

**Issue by lchjczw** [casbin/casibase#444]
建议将所有配置(包括前端配置)放到后端，后端提供一个公开接口来向前端提供配置，而前端总是只与一个后端API交互，而所有配置统一由后端管理，主要是casdoor的配置

It is recommended to put all configuration (including front-end configuration) on the back end, which provides a public interface to provide configuration to the front end, which always only interacts with a back-end API, and all configuration is managed by the back end，mainly casdoor configuration

**Comment by lchjczw** [comment]
尽量不要让前端去casdoor获取配置

Try not to let the front end go to Casdoor to get the configuration

**Comment by lchjczw** [comment]
when we need modify the config ,we just modfy the config on the beckend ,and then front is auto changed

**Comment by hsluoyz** [comment]
@lchjczw which config?

**Comment by lchjczw** [comment]
@hsluoyz    Casdoor SDk config

**Comment by lchjczw** [comment]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/12480676/158002901-647d0408-876c-4cb8-9b69-ab6433f1dcd0.png">

**Comment by hsluoyz** [comment]
@lchjczw Casdoor SDK config is better to be in frontend.
