### ISSUE TITLE
Bug: after favoring a topic, the relies have disappeared

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#459]
See: https://forum.casbin.com/t/134

https://user-images.githubusercontent.com/3787410/161584616-52be00b9-7c45-4977-bd56-f7bd35372233.mp4

**Comment by hsluoyz** [comment]
@RyaoChengfeng

**Comment by RyaoChengfeng** [comment]
The frontend will not request /get-replies when the URL ends with `#;` or `#`, this is a problem caused by a bug in the frontend part.
I think someone else is needed to work on it.

**Comment by hsluoyz** [comment]
@Nekotoxin
