### ISSUE TITLE
Fix Google SEO bad results

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#485]
See: https://www.google.com/search?q=site%3Aforum.casbin.com

![image](https://user-images.githubusercontent.com/3787410/162726674-893cd8b0-7143-4381-8f7a-1c00f05632f3.png)

![image](https://user-images.githubusercontent.com/3787410/162726870-5d9111ec-69a8-447a-813d-764958f8042a.png)

**Comment by hsluoyz** [comment]
@Nekotoxin

**Comment by zhenglin-charlie-li** [comment]
I think it's no longer a problem, because there is no 404 link and the content are up to date.

![image](https://user-images.githubusercontent.com/63448884/210934297-bbdcfa46-e639-4777-a9c0-02567cb09570.png)
