### ISSUE TITLE
Fix CI Docker error

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#488]
See: https://github.com/casbin/casnode/runs/6006738466?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/163174773-1f3ef185-d4a4-4848-b332-6e892dc54b48.png)

**Comment by hsluoyz** [comment]
@ComradeProgrammer @Nekotoxin

**Comment by ComradeProgrammer** [comment]
https://github.com/actions/checkout/issues/760
It is a known issue caused by github checkout plugin, (related with a announced git security vulnerability), and their maintainers are trying to fix
I suggest we should wait until they fix the problem for both casnode and casdoor
