### ISSUE TITLE
Bug: sometimes AT (@) people in reply box doesn't show the candidates

### ISSUE THREAD

**Issue by nomeguy** [casbin/casibase#500]
See: https://forum.casbin.com/t/709

![image](https://user-images.githubusercontent.com/85475922/165033296-cb14ab0d-d17c-4dbe-a0c5-afdbc42fdfbb.png)

**Comment by hsluoyz** [comment]
@Nekotoxin @RyaoChengfeng

**Comment by greenhandatsjtu** [comment]
@hsluoyz Hi there, I think I find the reason.
In `NewReplyBox.js`, `@` hint is using `this.props.memberList` to autocomplete candidates:
https://github.com/casbin/casnode/blob/e83296c61626e06b1ecadc545d968c76f9681e12/web/src/main/NewReplyBox.js#L198
And in `ReplyBox.js`, only **reply authors** are pushed to `memberList`:
https://github.com/casbin/casnode/blob/e83296c61626e06b1ecadc545d968c76f9681e12/web/src/main/ReplyBox.js#L200-L220
As the case of https://forum.casbin.com/t/709, there's no replies, so `this.props.memberList` is empty, which results in hint not showing any candidates.
I think we can try to also push topic creater to `memberList` to fix this issue,
