### ISSUE TITLE
SEO optimization: add a hidden reply page to offer better TDK info

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#503]
Previously, we added TDK to topic page: https://github.com/casbin/casnode/pull/474/files

The search engine can index our topic content now. But the reply contents are still not well indexed. We need to provide a "hidden" reply page. This page is hidden because it's useless for human users, but the search engine shoule see it and follow into that page.

The hidden link should be:

1. Clickable, human can enter the reply page (I don't know if it's not clickable, will the search engine also follow it)
2. Hidden (100% transparent)
3. Mouse pointer doesn't change on hover

So finally a human user can possibly accidently click and enter it, but they cannot see.

Like: https://forum.casbin.com/t/46#r_200

![image](https://user-images.githubusercontent.com/3787410/165975998-2d60db53-72a5-44fd-80a5-9241c87db8a6.png)

**Comment by Nekotoxin** [comment]
I will work on this
