### ISSUE TITLE
Using `name` as an association between applications will lead to disaster

### ISSUE THREAD

**Issue by nexmoe** [casbin/casibase#521]
Casnode uses `name` to get a user.
When I set my name to another user, I can use his or her account.
I think we should use `id` as the association.
![image](https://user-images.githubusercontent.com/16796652/172625362-e5dbeb3c-577e-4b70-be7c-60b008f81200.png)

![T%UE$R$WH2KM4 EJJUQV4NK](https://user-images.githubusercontent.com/16796652/172625276-058d7b07-96fa-434f-a794-45bd8c796afd.png)

**Comment by nexmoe** [comment]
Recurrence steps
Change your QQ name to hsluoyz
Then log in to casdoor with QQ

**Comment by hsluoyz** [comment]
@RyaoChengfeng

**Comment by RyaoChengfeng** [comment]
Fixed here: https://github.com/casdoor/casdoor/pull/785
