### ISSUE TITLE
How to use a Custom server as the authentication system?

### ISSUE THREAD

**Issue by curiosport** [casbin/casibase#543]
Hi, I'm not sure if I'm asking my questions correctly so I hope you'll bear with me.

I have seen the demo https://forum.casbin.com/

And it is just that forum that I need however I want to use my own system to verify users, so I guess I should not use cassdoor anymore right?

My questions are:

Can you give me an example using Go of how I would insert new users into casnode from an external application?

How do I disable casnode default authentication system to use only my own?

Where is the documentation for my authentication server to communicate with casnode?

The communication between my server and casnode is only to register and validate users nothing else.

Then casnode does the rest.

**Comment by hsluoyz** [comment]
@curiosport you must use Casdoor as the IAM in order to use Casnode

**Comment by curiosport** [comment]
> @curiosport you must use Casdoor as the IAM in order to use Casnode

Why? is there something specific in Casdoor that Casnode needs? because to my understanding Casdoor only verifies credentials and creates users, in my opinion nothing that can't be replaced by a custom implementation..

**Comment by hsluoyz** [comment]
@curiosport Casdoor and Casnode are from the same community, and Casnode's user table directly relies on Casdoor. That's how it is designed. We don't want to take efforts to support others because Casdoor is already enough to support nearly everything like OAuth, OIDC, SAML, CAS, etc. If you want to plug into another authentication server, you can do: Casnode -> Casdoor -> authentication server

**Comment by curiosport** [comment]
@hsluoyz That's what I thought, then I can have Casdoor be on the backend while my authentication server is the only thing users will see.

Ok, so my questions are the same, only instead of Casnode it would be Casdoor.

Where can I find the documentation to communicate with Casdoor? 

I found this link but I am not sure if that is all:
https://casdoor.org/docs/provider/oauth/CustomProvider

Can you at least help me with an example in Go of how I would send the credentials to Casdoor to verify and create new users?
