### ISSUE TITLE
Support discuz x3.4 Theme

### ISSUE THREAD

**Issue by deancn** [casbin/casibase#544]
Hi mainainer, 

We are trying to use casnode instead of Discuz X.   Our volunteer perfer to use the currently Discuz X theme.
The website is `https://bbs.baobeihuijia.com/`

![image](https://user-images.githubusercontent.com/1617384/192217675-d4a0defc-5045-4342-9790-e436f809dee6.png)
![image](https://user-images.githubusercontent.com/1617384/192217709-00351511-2661-453b-872d-9749cfb3003d.png)

**Comment by hsluoyz** [comment]
@xxrlzzz
