### ISSUE TITLE
Is it possible to isolate the code that handles the comment system?

### ISSUE THREAD

**Issue by curiosport** [casbin/casibase#556]
I am interested in using the comment system in another web project, is it possible to do so? or is the system quite dependent?

Please give me a general idea of how the code for the comment system is structured.

**Comment by hsluoyz** [comment]
@curiosport yes, see the solution based on iframe: https://oa.casbin.com/

![image](https://user-images.githubusercontent.com/3787410/200124244-effe5977-3e6c-478b-948a-2ac93904384b.png)


Code: https://github.com/casbin/casbin-oa/blob/544b607fe0662adaac46266d40241a46f3937674/web/src/App.js#L360-L392
