### ISSUE TITLE
The Casnode website can not be accessed worldwidely

### ISSUE THREAD

**Issue by zhenglin-charlie-li** [casbin/casibase#559]
https://forum.casbin.com/ appears to be inaccessible outside of China.

When I turn on my VPN, whichever country I choose, I cannot access https://forum.casbin.com/; it's always loading.

![image](https://user-images.githubusercontent.com/63448884/210937472-852e82ef-296f-4a85-9653-e81e411e9814.png)

What's more, when I am trying to solve this issue #512, I let several sitemap generators automatically generate a sitemap for our website, but none of them succeed. 3/3 of them returned a similar error, they just can not access our website. 

So, maybe we should check our deployment and check if it can be accessed worldwide.

**Comment by nomeguy** [comment]
already fixed
