### ISSUE TITLE
[bug] language switch button doesn't work like Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#602]
It doesn't change language immediately like Casdoor

![image](https://github.com/casbin/casibase/assets/3787410/bbd513e0-f9d3-4774-9f00-116f7d432ee8)

**Comment by okaysaga** [comment]
hey!! I think i am able to fix this bug , can you please assign this bug to me

**Comment by hsluoyz** [comment]
@okaysaga sure
