### ISSUE TITLE
feat: Can Casibase Support iFlytek spark as ai provider?

### ISSUE THREAD

**Issue by wintbiit** [casbin/casibase#634]
讯飞星火
API: https://www.xfyun.cn/doc/spark/Web.html

**Comment by kv-chiu** [comment]
There is already a branch working on this feature, coming soon.

**Comment by hsluoyz** [comment]
@WinterOfBit the Go example is here: https://xfyun-doc.cn-bj.ufileos.com/static%2F16903453488520286%2FSparkdemo.zip
