### ISSUE TITLE
casibase can save sub-model that do not match the current model

### ISSUE THREAD

**Issue by palp1tate** [casbin/casibase#655]
![image](https://github.com/casbin/casibase/assets/120303802/77f60161-d81f-4808-9d3d-e402aa38792a)

When I change the model,such as iFlytek，the sub-model can’t automatically match the current model

![image](https://github.com/casbin/casibase/assets/120303802/b72f8b44-575a-4f4a-82e7-5af105577482)

**Comment by hsluoyz** [comment]
@palp1tate refer to: https://github.com/casdoor/casdoor/blob/aab6a799feff343a18847435940a7c5315383199/web/src/ProviderEditPage.js#L439-L465
