### ISSUE TITLE
[Question] I need some help. After starting the cabibase image on an Ubuntu server, there's a URL redirection error when accessing it via IP

### ISSUE THREAD

**Issue by SHAO-QII** [casbin/casibase#725]
I would like to ask for assistance with an issue I'm experiencing. After launching a cabibase image on an Ubuntu server, when trying to access its HTTP service at http://<Ubuntu Server IP Address>:14000, there's a login error. What could be the reason for this?

![微信图片_20240226145701](https://github.com/casibase/casibase/assets/82205417/9b5ccb38-28f7-4324-b675-f3e91364d25d)

**Comment by hsluoyz** [comment]
@SHAO-QII you need to deploy your own Casdoor, see docs: https://casibase.org/docs/basic/casdoor-sso
