### ISSUE TITLE
Support for Qwen local API

### ISSUE THREAD

**Issue by MeditatorLiu** [casbin/casibase#731]
[Qwen models provide methods to deploy local API based on OpenAI API](https://github.com/QwenLM/Qwen), please add support for it.
We tried add a new provider, and input our local api in "Provider URL", but casibase seems ignore the "Provider URL" and stills tries to make post requests to OpenAI url.

**Comment by hsluoyz** [comment]
@MeditatorLiu you need to choose the "Local" --> "custom-model" for local models, see example: https://demo-admin.casibase.com/providers/provider_model_azure

![image](https://github.com/casibase/casibase/assets/3787410/d11b746c-e2e3-48f8-b2e3-67e27cdf8d7b)
