### ISSUE TITLE
Can I ask where the frondend source code is?

### ISSUE THREAD

**Issue by work7z** [casbin/casibase#786]
hi folks, this repo is wonderful!  

I wonder if it is fully opened source code? since i only found theres only Golang code, couldnt see frontend code.

**Comment by MartinRepo** [comment]
For frontend code, it is under the forlder called [web](https://github.com/casibase/casibase/tree/master/web)

**Comment by hsluoyz** [comment]
@work7z yes, please read the docs carefully: https://casibase.org/docs/basic/server-installation#download

![image](https://github.com/casibase/casibase/assets/3787410/ed3e8cf9-ee82-4ff7-8383-ceb143e7141e)


Frontend source code: https://github.com/casibase/casibase/tree/master/web
