### ISSUE TITLE
[feature] Add Qwen model provider to Casibase

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casibase#813]
See: https://bailian.console.aliyun.com/?

Both frontend and backend code needs to be addedd to support it

Like: https://github.com/casibase/casibase/issues?q=is%3Aissue+is%3Aclosed+model+provider

See Casibase: https://demo-admin.casibase.com/providers/provider_model_openrouter

![image](https://github.com/casibase/casibase/assets/3787410/f511c49d-ffbc-425d-874c-4027d6104677)

**Comment by lizzy-0323** [comment]
i would like to work on this issue.
