### ISSUE TITLE
custom-model will raise error: no encoding for model custom-model

### ISSUE THREAD

**Issue by BenDerPan** [casbin/casibase#856]
![image](https://github.com/casibase/casibase/assets/10903567/7d6d90fb-744c-4ed9-9038-1212d49c057a)

 use custom model and embedding provider(such as ollama/qwen:32b + litellm), this will happen, `custom-model ` is not a known model name for tiktoken libarary. but on the web page ,we cannot specifiy the compatible model name，such `as gpt-3.5-trubo`

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casibase/casibase/commit/df54200159b5db22550ad3003dd4747065a89809

**Comment by BenDerPan** [comment]
@hsluoyz still not work, 
`utils.go` also calls this function, and may other models token is not the same with `gpt-3.5-turbo`, if user can define the compatible token size model on the web ui  is much better, :)
```go
func GetTokenSize(model string, prompt string) (int, error) {
	tkm, err := tiktoken.EncodingForModel(model)
	if err != nil {
		return 0, err
	}

	token := tkm.Encode(prompt, nil, nil)
	res := len(token)
	return res, nil
}

```
