### ISSUE TITLE
Unable to click "+ new chat"

### ISSUE THREAD

**Issue by LifehackerLHZ** [casbin/casibase#891]
! [image] (https://github.com/casibase/casibase/assets/162850856/dbd20ae1-9acd-416d-8e2b-93e0e1a1b7e8)
The Add New Dialogue button has been unable to be clicked, and the configured large model cannot be used at all

**Comment by hsluoyz** [comment]
The new button will be disabled if you have too many empty chats (chats with no messages in it)
