### ISSUE TITLE
Issue on Dockerized Casdoor+Casibase

### ISSUE THREAD

**Issue by aulkiller** [casbin/casibase#939]
I've set up the app.conf and conf.js with correct id and endpoint on casdoor

![image](https://github.com/user-attachments/assets/06e4f752-b7d8-40a8-b93e-0910eec5f897)

Can you help me where i should start finding the solution? Thanks

![image](https://github.com/user-attachments/assets/96609cf8-efcb-4271-bc2b-9f5337e6da75)

**Comment by aulkiller** [comment]
Casdoor is working fine,

Here is casibase conf for Backend:
```
appname = casibase
httpport = 14000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = mysql
dataSourceName = root:my-secret-pw@tcp(host.docker.internal:3306)/
dbName = casibase
redisEndpoint =
isDemoMode = false
landingFolder =
casdoorEndpoint = http://host.docker.internal:8000
clientId = af6b5aa958822fb9dc33
clientSecret = 8bc3010c1c951c8d876b1f311a901ff8deeb93bc
casdoorOrganization = "casbin"
casdoorApplication = "app-casibase"
cacheDir = "C:/casibase_cache"
appDir = ""
audioStorageProvider = ""
providerDbName = ""
socks5Proxy = "127.0.0.1:10808"
publicDomain = ""
adminDomain = ""
```

for FrontEnd:

```
export const AuthConfig = {
  serverUrl: "http://localhost:8000",
  // serverUrl: "http://localhost:7001",
  clientId: "af6b5aa958822fb9dc33",
  appName: "app-casibase",
  organizationName: "casbin",
  redirectPath: "/callback",
};
```

**Comment by hsluoyz** [comment]
@aulkiller your cert public key file in your Casibase folder should match the one in your Casdoor cert list.

**Comment by aulkiller** [comment]
@hsluoyz Can you help me on which .pem to edit on Casibase? I saw quite many on /etc/ssl/certs folder or /etc/ssl

Because i've edit the /etc/ssl/cert.pem and added the public key on first line, still not working
I've also added /etc/ssl/certs/ca-cert-onprem.pem with the public key, still not working
Is there anything that i miss?

Public key is this one right?
![image](https://github.com/user-attachments/assets/5298f8b3-780b-4db4-9c25-a2bbc8054a4a)

**Comment by aulkiller** [comment]
![image](https://github.com/user-attachments/assets/1dc182c2-e054-4932-b812-e93cf34baa9a)

It even stated that it is already declared... Still not working (RSA Error)



Should i also handle the private key?

**Comment by aulkiller** [comment]
I see, i have replaced the pem casibase\controllers\token_jwt_key.pem and rebuilt the image, working fine now :) . Yeah adding the cert instruction to docs later on will be greatly appreciated.

Thank you
